target_server:
  ip: "127.0.0.1"
  port: 11011

# http bin
# target_server:
#   ip: "100.25.104.226"
#   port: 80

arp:
  log: false # boolean true/false to log ARP packets
  kind: "all" # options: "all", "request", "reply"

ipv4:
  log: true # boolean true/false to log IPv4 packets
  protocols: # list of protocols to log, options: "tcp", "udp", "icmp"
    - "tcp"
  include_headers: false # boolean true/false to include headers in logs

protocols:
  tcp:
    log: true # boolean true/false to log TCP packets

